#!/bin/bash

## Usage:
# ./up  => Start all services
# ./up frontend  => Start only frontend service
# ./up backend  => Start only backend service
##

APP=''
case $1 in
  frontend | backend)
    APP=$1
    ;;
esac

docker compose up $APP --build
