# uvicorn_config.toml
# Usage:
#   uvicorn app:main --config uvicorn_config.toml

[uvicorn]
host = "0.0.0.0"
port = 8080
workers = 4
loop = "uvloop"
http = "httptools"
reload = true
log_level = "info"
timeout_keep_alive = 10
proxy_headers = true
limit_concurrency = 100
limit_max_requests = 1000
