"""Add rent column to leases table.

Revision ID: 08ad04c7e791
Revises: 37bb5e7b0277
Create Date: 2024-12-17 19:22:03.881247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ad04c7e791'
down_revision: Union[str, None] = '37bb5e7b0277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rent', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.drop_column('rent')

    # ### end Alembic commands ###
