"""Add columns to units table.

Revision ID: 0b68bad72e35
Revises: 08ad04c7e791
Create Date: 2024-12-17 19:29:31.923108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b68bad72e35'
down_revision: Union[str, None] = '08ad04c7e791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vacant', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('bedrooms', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bathrooms', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('floor', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sqft', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_units_is_vacant'), ['is_vacant'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_is_vacant'))
        batch_op.drop_column('sqft')
        batch_op.drop_column('floor')
        batch_op.drop_column('bathrooms')
        batch_op.drop_column('bedrooms')
        batch_op.drop_column('is_vacant')

    # ### end Alembic commands ###
