"""Update properties: Make city, state, zip_code nullable

Revision ID: 0e2c4df2ad81
Revises: e714ee763363
Create Date: 2024-09-16 13:28:20.930551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2c4df2ad81'
down_revision: Union[str, None] = 'e714ee763363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
