"""Update floor_number column in units table.

Revision ID: 45af6cfd4fa9
Revises: ff9f69b8e87f
Create Date: 2024-12-17 19:43:22.394943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45af6cfd4fa9'
down_revision: Union[str, None] = 'ff9f69b8e87f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('floor_number', sa.Integer(), nullable=False))
        batch_op.drop_column('floor')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('floor_number')

    # ### end Alembic commands ###
