"""Remove unit_count column from buildings table

Revision ID: 4b676f159137
Revises: ece64264ef44
Create Date: 2025-01-16 23:24:20.671760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b676f159137'
down_revision: Union[str, None] = 'ece64264ef44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.drop_column('unit_count')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_count', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
