"""Update properties table, remove manager relationship

Revision ID: 836ee014d057
Revises: b5b99aba90fc
Create Date: 2025-01-16 18:47:51.719102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836ee014d057'
down_revision: Union[str, None] = 'b5b99aba90fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager', sa.String(), nullable=True))
        batch_op.drop_index('ix_properties_manager_id')
        batch_op.drop_constraint('properties_manager_id_fkey', type_='foreignkey')
        batch_op.drop_column('manager_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('properties_manager_id_fkey', 'users', ['manager_id'], ['id'])
        batch_op.create_index('ix_properties_manager_id', ['manager_id'], unique=False)
        batch_op.drop_column('manager')

    # ### end Alembic commands ###
