"""Add new columns to insurances table

Revision ID: a6021bc40686
Revises: bb1cc7b28926
Create Date: 2025-01-16 23:38:13.292476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6021bc40686'
down_revision: Union[str, None] = 'bb1cc7b28926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('premium', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('effective_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurances', schema=None) as batch_op:
        batch_op.drop_column('effective_date')
        batch_op.drop_column('premium')
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
