"""Add index to foreign key of resource tables

Revision ID: b5b99aba90fc
Revises: 3731b92508f0
Create Date: 2025-01-16 15:35:27.684257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5b99aba90fc'
down_revision: Union[str, None] = '3731b92508f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_buildings_property_id'), ['property_id'], unique=False)

    with op.batch_alter_table('insurances', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_insurances_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_leases_unit_id'), ['unit_id'], unique=False)

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_properties_manager_id'), ['manager_id'], unique=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_tenants_lease_id'), ['lease_id'], unique=False)

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_units_building_id'), ['building_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_building_id'))

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_lease_id'))

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_manager_id'))

    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leases_unit_id'))

    with op.batch_alter_table('insurances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurances_tenant_id'))

    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buildings_property_id'))

    # ### end Alembic commands ###
