"""Update properties: add name, unit_count, type

Revision ID: e714ee763363
Revises: a9619b65924a
Create Date: 2024-09-16 13:22:48.704123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e714ee763363'
down_revision: Union[str, None] = 'a9619b65924a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('name', sa.String(), nullable=False))
    op.add_column('properties', sa.Column('unit_count', sa.Integer(), nullable=False))
    op.add_column('properties', sa.Column('type', sa.String(), nullable=False))
    op.create_index(op.f('ix_properties_name'), 'properties', ['name'], unique=False)
    op.create_index(op.f('ix_properties_type'), 'properties', ['type'], unique=False)
    op.create_index(op.f('ix_properties_unit_count'), 'properties', ['unit_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_unit_count'), table_name='properties')
    op.drop_index(op.f('ix_properties_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_name'), table_name='properties')
    op.drop_column('properties', 'type')
    op.drop_column('properties', 'unit_count')
    op.drop_column('properties', 'name')
    # ### end Alembic commands ###
