"""Remove unnecessary indexes

Revision ID: ece64264ef44
Revises: 836ee014d057
Create Date: 2025-01-16 18:52:36.908241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece64264ef44'
down_revision: Union[str, None] = '836ee014d057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.drop_index('ix_buildings_name')

    with op.batch_alter_table('insurances', schema=None) as batch_op:
        batch_op.drop_index('ix_insurances_policy_number')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index('ix_properties_address')
        batch_op.drop_index('ix_properties_city')
        batch_op.drop_index('ix_properties_name')
        batch_op.drop_index('ix_properties_state')
        batch_op.drop_index('ix_properties_zip_code')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index('ix_tenants_email')
        batch_op.drop_index('ix_tenants_name')
        batch_op.drop_index('ix_tenants_phone')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_name', ['name'], unique=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index('ix_tenants_phone', ['phone'], unique=False)
        batch_op.create_index('ix_tenants_name', ['name'], unique=False)
        batch_op.create_index('ix_tenants_email', ['email'], unique=True)

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index('ix_properties_zip_code', ['zip_code'], unique=False)
        batch_op.create_index('ix_properties_state', ['state'], unique=False)
        batch_op.create_index('ix_properties_name', ['name'], unique=False)
        batch_op.create_index('ix_properties_city', ['city'], unique=False)
        batch_op.create_index('ix_properties_address', ['address'], unique=False)

    with op.batch_alter_table('insurances', schema=None) as batch_op:
        batch_op.create_index('ix_insurances_policy_number', ['policy_number'], unique=False)

    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.create_index('ix_buildings_name', ['name'], unique=False)

    # ### end Alembic commands ###
