"""Update unit_number column in units table.

Revision ID: ff9f69b8e87f
Revises: 179b091dbc20
Create Date: 2024-12-17 19:39:54.845064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9f69b8e87f'
down_revision: Union[str, None] = '179b091dbc20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_number', sa.String(), nullable=False))
        batch_op.drop_index('ix_units_number')
        batch_op.drop_column('number')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_index('ix_units_number', ['number'], unique=False)
        batch_op.drop_column('unit_number')

    # ### end Alembic commands ###
