#!/bin/bash

#
# Generate a new database migration.
#
# Usage:
#   ./migrate "Describe your changes"

if [ $# -gt 1 ]; then
  echo "Too many arguments."
elif [ -n "$1" ]; then
  alembic revision --autogenerate -m "$1"
else
  echo "Cannot have empty message."
fi
